<?php

namespace Hack\QuestionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BadgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgesRepository extends EntityRepository
{
}
