hack_questions:
    resource: "@HackQuestionsBundle/Controller/"
    type:     annotation
    prefix:   /questions

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
