hack_questions:
    resource: "@HackQuestionsBundle/Controller/"
    type:     annotation
    prefix:   /questions

#application/config/routing.yml
_security_check:
    pattern:  /login_check
_security_logout:
    pattern:  /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
